### ISSUE TITLE
Issues using source orbit to compile service programs using VSCode

### ISSUE THREAD

**Issue by kaspervanderhulst** [IBM/sourceorbit#76]
Hi, I am having issues trying to compile service programs in my project using source orbit. Normal programs seem to work, but the compile seems to completely skip my service programs. 

The steps i used to set this up are as follows:
1. I used the project explorer to migrate my sources from source libraries to my git project & IFS.
2. Installed source orbitter locally and on my ibm i system.
3. used so --init to set up my iproj.json file
4. used action setup to create the actions to Build with source orbiter

These steps all worked without any issues. But now when i try to compile the project using 'Build entire project with source orbiter' in visual studio code, my service programs seem to not get compiled.  I have tried with both Build entire project & Build current but both seem to not work. I have also tried to run the so -bf make & gmake commands in bash but still no luck. 

This is my output when running the build entire project using source orbiter:

```Running Action: Build entire project with Source Orbit 🔨 (2:26:41 PM)
Working directory: /home/EASKVHU/PRJ/test/vo/magazijn
Commands:
	so -bf make && /QOpenSys/pkgs/bin/gmake LIBL='EASTSTPGM T_NPST QTEMP QGPL EASTSTSRC T_OPSTS' BIN_LIB=EASKVHUTS OPT=*EVENTF

QDDLSRC/VOKLAV1_KLANTEN_BENL.view - No object found for reference 'voklapf'
QDDLSRC/VOKLAV2_KLANTEN_NL.view - No object found for reference 'voklapf'
QDDLSRC/VOKLLV1.SQL - No object found for reference 'vokllpf'
QDDLSRC/VOKLLV1.SQL - Failed to parse file.
QDDLSRC/VOKLLV1.SQL
TypeError: Cannot read properties of undefined (reading '0')
    at E (/QOpenSys/pkgs/lib/nodejs20/lib/node_modules/@ibm/sourceorbit/dist/index.js:3:89240)
    at t.Targets.createSqlTargets (/QOpenSys/pkgs/lib/nodejs20/lib/node_modules/@ibm/sourceorbit/dist/index.js:3:100578)
    at t.Targets.parseFile (/QOpenSys/pkgs/lib/nodejs20/lib/node_modules/@ibm/sourceorbit/dist/index.js:3:93416)
    at async /QOpenSys/pkgs/lib/nodejs20/lib/node_modules/@ibm/sourceorbit/dist/index.js:3:84692
[ERROR] Report this issue to us with an example: github.com/IBM/sourceorbit/issues
QDDLSRC/VOORKV1_ORDERS_PICKING_ALL.view - No object found for reference 'votwzpf'
QDDLSRC/VOORKV2_ORDERS_PICKING_BE.view - No object found for reference 'votwzpf'
QDDLSRC/VOORKV3_ORDERS_PICKING_NL.view - No object found for reference 'votwzpf'
QRPGLEMOD/lstver01s.sqlrpgle:42 - No object found for reference 'VOVERPF'
QRPGLEMOD/ordpck03s.sqlrpgle:67 - No object found for reference 'VOTWZL1'
QRPGLEMOD/ordpck03s.sqlrpgle:72 - No object found for reference 'VOTWZL1'
QRPGLEMOD/ordpck03s.sqlrpgle:76 - No object found for reference 'VOTWZL1'
QRPGLEMOD/ordpck03s.sqlrpgle:104 - No object found for reference 'VOMAGPF'
QRPGLEMOD/ordpck03s.sqlrpgle:117 - No object found for reference 'VOTWZPF'
QRPGLEMOD/ordpck03s.sqlrpgle:137 - No object found for reference 'VOORKLF'
make: Loaded project settings.
makefile:121: warning: overriding recipe for target '/QSYS.LIB/EASKVHUTS.LIB/VOKLATB.FILE'
makefile:105: warning: ignoring old recipe for target '/QSYS.LIB/EASKVHUTS.LIB/VOKLATB.FILE'
makefile:125: warning: overriding recipe for target '/QSYS.LIB/EASKVHUTS.LIB/VOORATB.FILE'
makefile:109: warning: ignoring old recipe for target '/QSYS.LIB/EASKVHUTS.LIB/VOORATB.FILE'
makefile:129: warning: overriding recipe for target '/QSYS.LIB/EASKVHUTS.LIB/VOORKTB.FILE'
makefile:113: warning: ignoring old recipe for target '/QSYS.LIB/EASKVHUTS.LIB/VOORKTB.FILE'
makefile:133: warning: overriding recipe for target '/QSYS.LIB/EASKVHUTS.LIB/VOORTTB.FILE'
makefile:117: warning: ignoring old recipe for target '/QSYS.LIB/EASKVHUTS.LIB/VOORTTB.FILE'
system -q "CRTLIB LIB(EASKVHUTS)"
gmake: [makefile:22: library] Error 1 (ignored)
liblist -c EASKVHUTS;\
liblist -a EASTSTPGM T_NPST QTEMP QGPL EASTSTSRC T_OPSTS;\
system "CRTBNDRPG PGM(EASKVHUTS/TEST) SRCSTMF('QRPGLESRC/test.pgm.rpgle') OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT) TGTCCSID(*JOB) BNDDIR((EASKVHUTS/APP)) DFTACTGRP(*NO)" > .logs/test.splf || \
(system "CPYTOSTMF FROMMBR('/QSYS.LIB/EASKVHUTS.LIB/EVFEVENT.FILE/TEST.MBR') TOSTMF('.evfevent/test.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; /QOpenSys/usr/bin/qsh -c 'exit 1')
liblist: 001-0081 Error CPF2103 found adding library QTEMP to library list.
CPC2206:  Eigendom object TEST type *MODULE in QTEMP is gewijzigd.
CPC2206:  Eigendom object TEST type *PGM in EASKVHUTS is gewijzigd.
RNS9304:  Program TEST placed in library EASKVHUTS. 00 highest severity. Created on 21/08/24 at 14:26:45.
CPC2206:  Eigendom object RETURNCODE type *DTAARA in QTEMP is gewijzigd.
CPC0904:  Gegevensgebied RETURNCODE is gemaakt in bibliotheek QTEMP.
CPC2206:  Eigendom object QZSHSYSTEM type *USRSPC in QTEMP is gewijzigd.

Fetching errors from .evfevent.
Downloaded files as part of Action: .evfevent/
```

As you can see my regular program is build, but my service programs (programs located in QRPGLEMOD) are not built. 

```iproj.son file:
{
  "description": "XXXXX ",
  "buildCommand": "/QOpenSys/pkgs/bin/makei build",
  "compileCommand": "/QOpenSys/pkgs/bin/makei compile -f {filename}",
  "preUsrlibl": [
    "EASTSTPGM",
    "T_NPST"
  ],
  "postUsrlibl": [
    "EASTSTSRC",
    "T_OPST"
  ],
  "compiles": {
    "pgm": {
      "becomes": "PGM",
      "command": "CRTPGM",
      "parameters": {
        "pgm": "$(BIN_LIB)/$*",
        "entmod": "$*",
        "module": "*MODULES",
        "tgtrls": "*CURRENT",
        "bnddir": "$(BNDDIR)",
        "actgrp": "*NEW"
      }
    },
    "pgm.rpgle": {
      "becomes": "PGM",
      "command": "CRTBNDRPG",
      "parameters": {
        "pgm": "$(BIN_LIB)/$*",
        "srcstmf": "'$<'",
        "option": "*EVENTF",
        "dbgview": "*SOURCE",
        "tgtrls": "*CURRENT",
        "tgtccsid": "*JOB",
        "bnddir": "$(BNDDIR)",
        "dftactgrp": "*NO"
      }
    },
    "pgm.sqlrpgle": {
      "becomes": "PGM",
      "command": "CRTSQLRPGI",
      "parameters": {
        "obj": "$(BIN_LIB)/$*",
        "srcstmf": "'$<'",
        "commit": "*NONE",
        "dbgview": "*SOURCE",
        "option": "*EVENTF",
        "rpgppopt": "*LVL2",
        "compileopt": "TGTCCSID(*JOB) BNDDIR($(BNDDIR)) DFTACTGRP(*no)"
      }
    },
    "rpgle": {
      "becomes": "MODULE",
      "command": "CRTRPGMOD",
      "parameters": {
        "module": "$(BIN_LIB)/$*",
        "srcstmf": "'$<'",
        "option": "*EVENTF",
        "dbgview": "*SOURCE",
        "tgtrls": "*CURRENT",
        "tgtccsid": "*JOB"
      }
    },
    "sqlrpgle": {
      "becomes": "MODULE",
      "command": "CRTSQLRPGI",
      "parameters": {
        "obj": "$(BIN_LIB)/$*",
        "srcstmf": "'$<'",
        "commit": "*NONE",
        "dbgview": "*SOURCE",
        "compileopt": "'TGTCCSID(*JOB)'",
        "rpgppopt": "*LVL2",
        "option": "*EVENTF",
        "objtype": "*MODULE"
      }
    },
    "pgm.clle": {
      "becomes": "PGM",
      "command": "CRTBNDCL",
      "parameters": {
        "pgm": "$(BIN_LIB)/$*",
        "srcstmf": "'$<'",
        "option": "*EVENTF",
        "dbgview": "*SOURCE",
        "tgtrls": "*CURRENT",
        "dftactgrp": "*NO"
      }
    },
    "dspf": {
      "becomes": "FILE",
      "member": true,
      "command": "CRTDSPF",
      "parameters": {
        "file": "$(BIN_LIB)/$*",
        "srcfile": "$(BIN_LIB)/$(SRCPF)",
        "srcmbr": "$*",
        "option": "*EVENTF"
      }
    },
    "prtf": {
      "becomes": "FILE",
      "member": true,
      "command": "CRTPRTF",
      "parameters": {
        "file": "$(BIN_LIB)/$*",
        "srcfile": "$(BIN_LIB)/$(SRCPF)",
        "srcmbr": "$*",
        "option": "*EVENTF"
      }
    },
    "cmd": {
      "becomes": "CMD",
      "member": true,
      "command": "CRTCMD",
      "parameters": {
        "cmd": "$(BIN_LIB)/$*",
        "pgm": "$(BIN_LIB)/$*",
        "srcfile": "$(BIN_LIB)/$(SRCPF)",
        "option": "*EVENTF"
      }
    },
    "sql": {
      "becomes": "FILE",
      "command": "RUNSQLSTM",
      "parameters": {
        "srcstmf": "'$<'",
        "commit": "*NONE"
      }
    },
    "sqludf": {
      "becomes": "SRVPGM",
      "command": "RUNSQLSTM",
      "parameters": {
        "srcstmf": "'$<'",
        "commit": "*NONE"
      }
    },
    "table": {
      "becomes": "FILE",
      "command": "RUNSQLSTM",
      "parameters": {
        "srcstmf": "'$<'",
        "commit": "*NONE"
      }
    },
    "binder": {
      "becomes": "SRVPGM",
      "preCommands": [
        "-system -q \"CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))\""
      ],
      "command": "CRTSRVPGM",
      "parameters": {
        "srvpgm": "$(BIN_LIB)/$*",
        "module": "*MODULES",
        "srcstmf": "'$<'",
        "bnddir": "$(BNDDIR)",
        "replace": "*YES"
      },
      "postCommands": [
        "-system -q \"ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/$* *SRVPGM *IMMED))\""
      ]
    },
    "bnd": {
      "becomes": "SRVPGM",
      "preCommands": [
        "-system -q \"CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))\""
      ],
      "command": "CRTSRVPGM",
      "parameters": {
        "srvpgm": "$(BIN_LIB)/$*",
        "module": "*MODULES",
        "srcstmf": "'$<'",
        "bnddir": "$(BNDDIR)",
        "replace": "*YES"
      },
      "postCommands": [
        "-system -q \"ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/$* *SRVPGM *IMMED))\""
      ]
    },
    "srvpgm": {
      "becomes": "SRVPGM",
      "preCommands": [
        "-system -q \"CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))\"",
        "-system -q \"RMVBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ(($(BIN_LIB)/$*))\"",
        "-system \"DLTOBJ OBJ($(BIN_LIB)/$*) OBJTYPE(*SRVPGM)\""
      ],
      "command": "CRTSRVPGM",
      "parameters": {
        "srvpgm": "$(BIN_LIB)/$*",
        "module": "*MODULES",
        "srcstmf": "'$<'",
        "bnddir": "$(BNDDIR)"
      },
      "postCommands": [
        "-system -q \"ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/$* *SRVPGM *IMMED))\""
      ]
    },
    "bnddir": {
      "sourceOptional": true,
      "becomes": "BNDDIR",
      "preCommands": [
        "-system -q \"CRTBNDDIR BNDDIR($(BIN_LIB)/$*)\"",
        "-system -q \"ADDBNDDIRE BNDDIR($(BIN_LIB)/$*) OBJ($(patsubst %.SRVPGM,(*LIBL/% *SRVPGM *IMMED),$(notdir $^)))\""
      ]
    },
    "dtaara": {
      "becomes": "DTAARA",
      "commandSource": true
    },
    "mnucmd": {
      "becomes": "MENU",
      "member": true,
      "command": "CRTMNU",
      "parameters": {
        "menu": "$(BIN_LIB)/$*",
        "type": "*DSPF",
        "dspf": "$(BIN_LIB)/$*"
      }
    },
    "pf": {
      "becomes": "FILE",
      "member": true,
      "command": "CRTPF",
      "parameters": {
        "file": "$(BIN_LIB)/$*",
        "srcfile": "$(BIN_LIB)/$(SRCPF)",
        "option": "*EVENTF"
      }
    },
    "lf": {
      "becomes": "FILE",
      "member": true,
      "command": "CRTLF",
      "parameters": {
        "file": "$(BIN_LIB)/$*",
        "srcfile": "$(BIN_LIB)/$(SRCPF)",
        "option": "*EVENTF"
      }
    }
  }
}
```

makefile:
```
BIN_LIB=DEV
APP_BNDDIR=APP
LIBL=$(BIN_LIB)

INCDIR=""
BNDDIR=($(BIN_LIB)/$(APP_BNDDIR))
PREPATH=/QSYS.LIB/$(BIN_LIB).LIB
SHELL=/QOpenSys/usr/bin/qsh

all: .logs .evfevent library $(PREPATH)/$(APP_BNDDIR).BNDDIR $(PREPATH)/TEST.PGM

$(PREPATH)/VOKLAV1.FILE: $(PREPATH)/VOKLATB.FILE
$(PREPATH)/VOORKV1.FILE: $(PREPATH)/VOORKTB.FILE $(PREPATH)/VOORATB.FILE $(PREPATH)/VOORTTB.FILE $(PREPATH)/VOKLAV1.FILE
$(PREPATH)/VOORKV2.FILE: $(PREPATH)/VOORKTB.FILE $(PREPATH)/VOORATB.FILE $(PREPATH)/VOORTTB.FILE $(PREPATH)/VOKLATB.FILE
$(PREPATH)/VOORKV3.FILE: $(PREPATH)/VOORKTB.FILE $(PREPATH)/VOORATB.FILE $(PREPATH)/VOORTTB.FILE $(PREPATH)/VOKLAV2.FILE

.logs:
	mkdir .logs
.evfevent:
	mkdir .evfevent
library:
	-system -q "CRTLIB LIB($(BIN_LIB))"


$(PREPATH)/TEST.PGM: QRPGLESRC/test.pgm.rpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTBNDRPG PGM($(BIN_LIB)/TEST) SRCSTMF('QRPGLESRC/test.pgm.rpgle') OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT) TGTCCSID(*JOB) BNDDIR($(BNDDIR)) DFTACTGRP(*NO)" > .logs/test.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/TEST.MBR') TOSTMF('.evfevent/test.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')


$(PREPATH)/APIERR01S.MODULE: QRPGLEMOD/apierr01s.rpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTRPGMOD MODULE($(BIN_LIB)/APIERR01S) SRCSTMF('QRPGLEMOD/apierr01s.rpgle') OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT) TGTCCSID(*JOB)" > .logs/apierr01s.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/APIERR01S.MBR') TOSTMF('.evfevent/apierr01s.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')
$(PREPATH)/APIVAL01S.MODULE: QRPGLEMOD/apival01s.rpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTRPGMOD MODULE($(BIN_LIB)/APIVAL01S) SRCSTMF('QRPGLEMOD/apival01s.rpgle') OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT) TGTCCSID(*JOB)" > .logs/apival01s.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/APIVAL01S.MBR') TOSTMF('.evfevent/apival01s.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')

$(PREPATH)/APIUTL01S.MODULE: QRPGLEMOD/apiutl01s.sqlrpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSQLRPGI OBJ($(BIN_LIB)/APIUTL01S) SRCSTMF('QRPGLEMOD/apiutl01s.sqlrpgle') COMMIT(*NONE) DBGVIEW(*SOURCE) COMPILEOPT('TGTCCSID(*JOB)') RPGPPOPT(*LVL2) OPTION(*EVENTF) OBJTYPE(*MODULE)" > .logs/apiutl01s.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/APIUTL01S.MBR') TOSTMF('.evfevent/apiutl01s.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')
$(PREPATH)/APIVAL02S.MODULE: QRPGLESRC/apival02s.sqlrpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSQLRPGI OBJ($(BIN_LIB)/APIVAL02S) SRCSTMF('QRPGLESRC/apival02s.sqlrpgle') COMMIT(*NONE) DBGVIEW(*SOURCE) COMPILEOPT('TGTCCSID(*JOB)') RPGPPOPT(*LVL2) OPTION(*EVENTF) OBJTYPE(*MODULE)" > .logs/apival02s.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/APIVAL02S.MBR') TOSTMF('.evfevent/apival02s.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')
$(PREPATH)/APIVAL03S.MODULE: QRPGLEMOD/apival03s.sqlrpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSQLRPGI OBJ($(BIN_LIB)/APIVAL03S) SRCSTMF('QRPGLEMOD/apival03s.sqlrpgle') COMMIT(*NONE) DBGVIEW(*SOURCE) COMPILEOPT('TGTCCSID(*JOB)') RPGPPOPT(*LVL2) OPTION(*EVENTF) OBJTYPE(*MODULE)" > .logs/apival03s.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/APIVAL03S.MBR') TOSTMF('.evfevent/apival03s.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')
$(PREPATH)/APIVAL04S.MODULE: QRPGLEMOD/apival04s.sqlrpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSQLRPGI OBJ($(BIN_LIB)/APIVAL04S) SRCSTMF('QRPGLEMOD/apival04s.sqlrpgle') COMMIT(*NONE) DBGVIEW(*SOURCE) COMPILEOPT('TGTCCSID(*JOB)') RPGPPOPT(*LVL2) OPTION(*EVENTF) OBJTYPE(*MODULE)" > .logs/apival04s.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/APIVAL04S.MBR') TOSTMF('.evfevent/apival04s.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')
$(PREPATH)/APIVAL05S.MODULE: QRPGLEMOD/apival05s.sqlrpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSQLRPGI OBJ($(BIN_LIB)/APIVAL05S) SRCSTMF('QRPGLEMOD/apival05s.sqlrpgle') COMMIT(*NONE) DBGVIEW(*SOURCE) COMPILEOPT('TGTCCSID(*JOB)') RPGPPOPT(*LVL2) OPTION(*EVENTF) OBJTYPE(*MODULE)" > .logs/apival05s.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/APIVAL05S.MBR') TOSTMF('.evfevent/apival05s.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')
$(PREPATH)/LSTVER01S.MODULE: QRPGLEMOD/lstver01s.sqlrpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSQLRPGI OBJ($(BIN_LIB)/LSTVER01S) SRCSTMF('QRPGLEMOD/lstver01s.sqlrpgle') COMMIT(*NONE) DBGVIEW(*SOURCE) COMPILEOPT('TGTCCSID(*JOB)') RPGPPOPT(*LVL2) OPTION(*EVENTF) OBJTYPE(*MODULE)" > .logs/lstver01s.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/LSTVER01S.MBR') TOSTMF('.evfevent/lstver01s.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')
$(PREPATH)/ORDCON01S.MODULE: QRPGLEMOD/ordcon01s.sqlrpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSQLRPGI OBJ($(BIN_LIB)/ORDCON01S) SRCSTMF('QRPGLEMOD/ordcon01s.sqlrpgle') COMMIT(*NONE) DBGVIEW(*SOURCE) COMPILEOPT('TGTCCSID(*JOB)') RPGPPOPT(*LVL2) OPTION(*EVENTF) OBJTYPE(*MODULE)" > .logs/ordcon01s.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/ORDCON01S.MBR') TOSTMF('.evfevent/ordcon01s.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')
$(PREPATH)/ORDPCK01S.MODULE: QRPGLEMOD/ordpck01s.sqlrpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSQLRPGI OBJ($(BIN_LIB)/ORDPCK01S) SRCSTMF('QRPGLEMOD/ordpck01s.sqlrpgle') COMMIT(*NONE) DBGVIEW(*SOURCE) COMPILEOPT('TGTCCSID(*JOB)') RPGPPOPT(*LVL2) OPTION(*EVENTF) OBJTYPE(*MODULE)" > .logs/ordpck01s.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/ORDPCK01S.MBR') TOSTMF('.evfevent/ordpck01s.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')
$(PREPATH)/ORDPCK02S.MODULE: QRPGLEMOD/ordpck02s.sqlrpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSQLRPGI OBJ($(BIN_LIB)/ORDPCK02S) SRCSTMF('QRPGLEMOD/ordpck02s.sqlrpgle') COMMIT(*NONE) DBGVIEW(*SOURCE) COMPILEOPT('TGTCCSID(*JOB)') RPGPPOPT(*LVL2) OPTION(*EVENTF) OBJTYPE(*MODULE)" > .logs/ordpck02s.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/ORDPCK02S.MBR') TOSTMF('.evfevent/ordpck02s.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')
$(PREPATH)/ORDPCK03S.MODULE: QRPGLEMOD/ordpck03s.sqlrpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSQLRPGI OBJ($(BIN_LIB)/ORDPCK03S) SRCSTMF('QRPGLEMOD/ordpck03s.sqlrpgle') COMMIT(*NONE) DBGVIEW(*SOURCE) COMPILEOPT('TGTCCSID(*JOB)') RPGPPOPT(*LVL2) OPTION(*EVENTF) OBJTYPE(*MODULE)" > .logs/ordpck03s.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/ORDPCK03S.MBR') TOSTMF('.evfevent/ordpck03s.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')
$(PREPATH)/APIVAL02S.MODULE: QRPGLESRC/apival02s.sqlrpgle
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSQLRPGI OBJ($(BIN_LIB)/APIVAL02S) SRCSTMF('QRPGLESRC/apival02s.sqlrpgle') COMMIT(*NONE) DBGVIEW(*SOURCE) COMPILEOPT('TGTCCSID(*JOB)') RPGPPOPT(*LVL2) OPTION(*EVENTF) OBJTYPE(*MODULE)" > .logs/apival02s.splf || \
	(system "CPYTOSTMF FROMMBR('$(PREPATH)/EVFEVENT.FILE/APIVAL02S.MBR') TOSTMF('.evfevent/apival02s.evfevent') DBFCCSID(*FILE) STMFCCSID(1208) STMFOPT(*REPLACE)"; $(SHELL) -c 'exit 1')





$(PREPATH)/VOKLLV1.FILE: QDDLSRC/VOKLLV1.SQL
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "RUNSQLSTM SRCSTMF('QDDLSRC/VOKLLV1.SQL') COMMIT(*NONE)" > .logs/vokllv1.splf


$(PREPATH)/VOKLATB.FILE: QSQLSRC/voklatb.table
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "RUNSQLSTM SRCSTMF('QSQLSRC/voklatb.table') COMMIT(*NONE)" > .logs/voklatb.splf
$(PREPATH)/VOORATB.FILE: QSQLSRC/vooratb.table
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "RUNSQLSTM SRCSTMF('QSQLSRC/vooratb.table') COMMIT(*NONE)" > .logs/vooratb.splf
$(PREPATH)/VOORKTB.FILE: QSQLSRC/voorktb.table
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "RUNSQLSTM SRCSTMF('QSQLSRC/voorktb.table') COMMIT(*NONE)" > .logs/voorktb.splf
$(PREPATH)/VOORTTB.FILE: QSQLSRC/voorttb.table
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "RUNSQLSTM SRCSTMF('QSQLSRC/voorttb.table') COMMIT(*NONE)" > .logs/voorttb.splf
$(PREPATH)/VOKLATB.FILE: QSQLSRC/voklatb.table
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "RUNSQLSTM SRCSTMF('QSQLSRC/voklatb.table') COMMIT(*NONE)" > .logs/voklatb.splf
$(PREPATH)/VOORATB.FILE: QSQLSRC/vooratb.table
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "RUNSQLSTM SRCSTMF('QSQLSRC/vooratb.table') COMMIT(*NONE)" > .logs/vooratb.splf
$(PREPATH)/VOORKTB.FILE: QSQLSRC/voorktb.table
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "RUNSQLSTM SRCSTMF('QSQLSRC/voorktb.table') COMMIT(*NONE)" > .logs/voorktb.splf
$(PREPATH)/VOORTTB.FILE: QSQLSRC/voorttb.table
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "RUNSQLSTM SRCSTMF('QSQLSRC/voorttb.table') COMMIT(*NONE)" > .logs/voorttb.splf


$(PREPATH)/APIERR01S.SRVPGM: QSRVSRC/apierr01s.bnd
	-system -q "CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))"
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSRVPGM SRVPGM($(BIN_LIB)/APIERR01S) MODULE(*MODULES) SRCSTMF('QSRVSRC/apierr01s.bnd') BNDDIR($(BNDDIR)) REPLACE(*YES)" > .logs/apierr01s.splf
	-system -q "ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/APIERR01S *SRVPGM *IMMED))"
$(PREPATH)/APIUTL01S.SRVPGM: QSRVSRC/apiutl01s.bnd
	-system -q "CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))"
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSRVPGM SRVPGM($(BIN_LIB)/APIUTL01S) MODULE(*MODULES) SRCSTMF('QSRVSRC/apiutl01s.bnd') BNDDIR($(BNDDIR)) REPLACE(*YES)" > .logs/apiutl01s.splf
	-system -q "ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/APIUTL01S *SRVPGM *IMMED))"
$(PREPATH)/APIVAL01S.SRVPGM: QSRVSRC/apival01s.bnd
	-system -q "CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))"
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSRVPGM SRVPGM($(BIN_LIB)/APIVAL01S) MODULE(*MODULES) SRCSTMF('QSRVSRC/apival01s.bnd') BNDDIR($(BNDDIR)) REPLACE(*YES)" > .logs/apival01s.splf
	-system -q "ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/APIVAL01S *SRVPGM *IMMED))"
$(PREPATH)/APIVAL02S.SRVPGM: QSRVSRC/apival02s.bnd
	-system -q "CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))"
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSRVPGM SRVPGM($(BIN_LIB)/APIVAL02S) MODULE(*MODULES) SRCSTMF('QSRVSRC/apival02s.bnd') BNDDIR($(BNDDIR)) REPLACE(*YES)" > .logs/apival02s.splf
	-system -q "ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/APIVAL02S *SRVPGM *IMMED))"
$(PREPATH)/APIVAL03S.SRVPGM: QSRVSRC/apival03s.bnd
	-system -q "CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))"
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSRVPGM SRVPGM($(BIN_LIB)/APIVAL03S) MODULE(*MODULES) SRCSTMF('QSRVSRC/apival03s.bnd') BNDDIR($(BNDDIR)) REPLACE(*YES)" > .logs/apival03s.splf
	-system -q "ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/APIVAL03S *SRVPGM *IMMED))"
$(PREPATH)/APIVAL04S.SRVPGM: QSRVSRC/apival04s.bnd
	-system -q "CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))"
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSRVPGM SRVPGM($(BIN_LIB)/APIVAL04S) MODULE(*MODULES) SRCSTMF('QSRVSRC/apival04s.bnd') BNDDIR($(BNDDIR)) REPLACE(*YES)" > .logs/apival04s.splf
	-system -q "ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/APIVAL04S *SRVPGM *IMMED))"
$(PREPATH)/APIVAL05S.SRVPGM: QSRVSRC/apival05s.bnd
	-system -q "CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))"
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSRVPGM SRVPGM($(BIN_LIB)/APIVAL05S) MODULE(*MODULES) SRCSTMF('QSRVSRC/apival05s.bnd') BNDDIR($(BNDDIR)) REPLACE(*YES)" > .logs/apival05s.splf
	-system -q "ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/APIVAL05S *SRVPGM *IMMED))"
$(PREPATH)/LSTVER01S.SRVPGM: QSRVSRC/lstver01s.bnd
	-system -q "CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))"
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSRVPGM SRVPGM($(BIN_LIB)/LSTVER01S) MODULE(*MODULES) SRCSTMF('QSRVSRC/lstver01s.bnd') BNDDIR($(BNDDIR)) REPLACE(*YES)" > .logs/lstver01s.splf
	-system -q "ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/LSTVER01S *SRVPGM *IMMED))"
$(PREPATH)/ORDCON01S.SRVPGM: QSRVSRC/ordcon01s.bnd
	-system -q "CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))"
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSRVPGM SRVPGM($(BIN_LIB)/ORDCON01S) MODULE(*MODULES) SRCSTMF('QSRVSRC/ordcon01s.bnd') BNDDIR($(BNDDIR)) REPLACE(*YES)" > .logs/ordcon01s.splf
	-system -q "ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/ORDCON01S *SRVPGM *IMMED))"
$(PREPATH)/ORDPCK01S.SRVPGM: QSRVSRC/ordpck01s.bnd
	-system -q "CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))"
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSRVPGM SRVPGM($(BIN_LIB)/ORDPCK01S) MODULE(*MODULES) SRCSTMF('QSRVSRC/ordpck01s.bnd') BNDDIR($(BNDDIR)) REPLACE(*YES)" > .logs/ordpck01s.splf
	-system -q "ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/ORDPCK01S *SRVPGM *IMMED))"
$(PREPATH)/ORDPCK02S.SRVPGM: QSRVSRC/ordpck02s.bnd
	-system -q "CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))"
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSRVPGM SRVPGM($(BIN_LIB)/ORDPCK02S) MODULE(*MODULES) SRCSTMF('QSRVSRC/ordpck02s.bnd') BNDDIR($(BNDDIR)) REPLACE(*YES)" > .logs/ordpck02s.splf
	-system -q "ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/ORDPCK02S *SRVPGM *IMMED))"
$(PREPATH)/ORDPCK03S.SRVPGM: QSRVSRC/ordpck03s.bnd
	-system -q "CRTBNDDIR BNDDIR($(BIN_LIB)/$(APP_BNDDIR))"
	liblist -c $(BIN_LIB);\
	liblist -a $(LIBL);\
	system "CRTSRVPGM SRVPGM($(BIN_LIB)/ORDPCK03S) MODULE(*MODULES) SRCSTMF('QSRVSRC/ordpck03s.bnd') BNDDIR($(BNDDIR)) REPLACE(*YES)" > .logs/ordpck03s.splf
	-system -q "ADDBNDDIRE BNDDIR($(BIN_LIB)/$(APP_BNDDIR)) OBJ((*LIBL/ORDPCK03S *SRVPGM *IMMED))"


$(PREPATH)/%.BNDDIR: 
	-system -q "CRTBNDDIR BNDDIR($(BIN_LIB)/$*)"
	-system -q "ADDBNDDIRE BNDDIR($(BIN_LIB)/$*) OBJ($(patsubst %.SRVPGM,(*LIBL/% *SRVPGM *IMMED),$(notdir $^)))"
```

Let me know if any additional info is required!

**Comment by worksofliam** [comment]
Try running `so --verbose` and share the logs here. That might show off some more detail!

**Comment by kaspervanderhulst** [comment]
```
PS C:\Users\kvhu\Documents\Klanten\Van opstal\rpg-backend\van-opstal-magazijn> so --verbose
VOKLATB.FILE: QDDLSRC\voklatb.table

VOKLAV1.FILE: QDDLSRC\VOKLAV1_KLANTEN_BENL.view
QDDLSRC\VOKLAV1_KLANTEN_BENL.view - No object found for reference 'voklapf'
Depends on: VOKLATB.FILE

VOKLAV2.FILE: QDDLSRC\VOKLAV2_KLANTEN_NL.view
QDDLSRC\VOKLAV2_KLANTEN_NL.view - No object found for reference 'voklapf'

VOKLLV1.FILE: QDDLSRC\VOKLLV1.SQL
QDDLSRC\VOKLLV1.SQL - No object found for reference 'vokllpf'
QDDLSRC\VOKLLV1.SQL - Failed to parse file.
QDDLSRC\VOKLLV1.SQL
TypeError: Cannot read properties of undefined (reading '0')
    at E (C:\Users\kvhu\npm-global\node_modules\@ibm\sourceorbit\dist\index.js:3:89240)
    at t.Targets.createSqlTargets (C:\Users\kvhu\npm-global\node_modules\@ibm\sourceorbit\dist\index.js:3:100578)
    at t.Targets.parseFile (C:\Users\kvhu\npm-global\node_modules\@ibm\sourceorbit\dist\index.js:3:93416)
    at async C:\Users\kvhu\npm-global\node_modules\@ibm\sourceorbit\dist\index.js:3:84692

[ERROR] Report this issue to us with an example: github.com/IBM/sourceorbit/issues
VOORATB.FILE: QDDLSRC\vooratb.table

VOORKTB.FILE: QDDLSRC\voorktb.table

VOORKV1.FILE: QDDLSRC\VOORKV1_ORDERS_PICKING_ALL.view
QDDLSRC\VOORKV1_ORDERS_PICKING_ALL.view - No object found for reference 'votwzpf'
Depends on: VOORKTB.FILE VOORATB.FILE VOORTTB.FILE VOKLAV1.FILE

VOORKV2.FILE: QDDLSRC\VOORKV2_ORDERS_PICKING_BE.view
QDDLSRC\VOORKV2_ORDERS_PICKING_BE.view - No object found for reference 'votwzpf'
Depends on: VOORKTB.FILE VOORATB.FILE VOORTTB.FILE VOKLATB.FILE

VOORKV3.FILE: QDDLSRC\VOORKV3_ORDERS_PICKING_NL.view
QDDLSRC\VOORKV3_ORDERS_PICKING_NL.view - No object found for reference 'votwzpf'
Depends on: VOORKTB.FILE VOORATB.FILE VOORTTB.FILE VOKLAV2.FILE

VOORTTB.FILE: QDDLSRC\voorttb.table

APIERR01S.MODULE: QRPGLEMOD\apierr01s.rpgle
QRPGLEMOD\apierr01s.rpgle:20 - Include at line 20 found, to path 'QPROTO/apierr01s.rpgleinc'
QRPGLEMOD\apierr01s.rpgle:19 - Include at line 19 found, to path 'QPROTO/apival01s.rpgleinc'

APIUTL01S.MODULE: QRPGLEMOD\apiutl01s.sqlrpgle
QRPGLEMOD\apiutl01s.sqlrpgle:22 - Include at line 22 found, to path 'QPROTO/sql_h.rpgleinc'
QRPGLEMOD\apiutl01s.sqlrpgle:21 - Include at line 21 found, to path 'QPROTO/apiutl01s.rpgleinc'

APIVAL01S.MODULE: QRPGLEMOD\apival01s.rpgle
QRPGLEMOD\apival01s.rpgle:26 - Include at line 26 found, to path 'QPROTO/sql_h.rpgleinc'
QRPGLEMOD\apival01s.rpgle:25 - Include at line 25 found, to path 'QPROTO/apierr01s.rpgleinc'
QRPGLEMOD\apival01s.rpgle:24 - Include at line 24 found, to path 'QPROTO/apival05s.rpgleinc'
QRPGLEMOD\apival01s.rpgle:23 - Include at line 23 found, to path 'QPROTO/apival04s.rpgleinc'
QRPGLEMOD\apival01s.rpgle:22 - Include at line 22 found, to path 'QPROTO/apival03s.rpgleinc'
QRPGLEMOD\apival01s.rpgle:21 - Include at line 21 found, to path 'QPROTO/apival02s.rpgleinc'
QRPGLEMOD\apival01s.rpgle:20 - Include at line 20 found, to path 'QPROTO/apival01s.rpgleinc'
QRPGLEMOD\apival01s.rpgle - has the BNDDIR keyword. 'binders' property in iproj.json should be used instead.

APIVAL02S.MODULE: QRPGLEMOD\apival02s.sqlrpgle
QRPGLEMOD\apival02s.sqlrpgle:21 - Include at line 21 found, to path 'QPROTO/sql_h.rpgleinc'
QRPGLEMOD\apival02s.sqlrpgle:20 - Include at line 20 found, to path 'QPROTO/apival02s.rpgleinc'
QRPGLEMOD\apival02s.sqlrpgle:19 - Include at line 19 found, to path 'QPROTO/apival01s.rpgleinc'

APIVAL03S.MODULE: QRPGLEMOD\apival03s.sqlrpgle
QRPGLEMOD\apival03s.sqlrpgle:21 - Include at line 21 found, to path 'QPROTO/sql_h.rpgleinc'
QRPGLEMOD\apival03s.sqlrpgle:20 - Include at line 20 found, to path 'QPROTO/apival03s.rpgleinc'
QRPGLEMOD\apival03s.sqlrpgle:19 - Include at line 19 found, to path 'QPROTO/apival01s.rpgleinc'

APIVAL04S.MODULE: QRPGLEMOD\apival04s.sqlrpgle
QRPGLEMOD\apival04s.sqlrpgle:21 - Include at line 21 found, to path 'QPROTO/sql_h.rpgleinc'
QRPGLEMOD\apival04s.sqlrpgle:20 - Include at line 20 found, to path 'QPROTO/apival04s.rpgleinc'
QRPGLEMOD\apival04s.sqlrpgle:19 - Include at line 19 found, to path 'QPROTO/apival01s.rpgleinc'

APIVAL05S.MODULE: QRPGLEMOD\apival05s.sqlrpgle
QRPGLEMOD\apival05s.sqlrpgle:21 - Include at line 21 found, to path 'QPROTO/sql_h.rpgleinc'
QRPGLEMOD\apival05s.sqlrpgle:20 - Include at line 20 found, to path 'QPROTO/apival05s.rpgleinc'
QRPGLEMOD\apival05s.sqlrpgle:19 - Include at line 19 found, to path 'QPROTO/apival01s.rpgleinc'

LSTVER01S.MODULE: QRPGLEMOD\lstver01s.sqlrpgle
QRPGLEMOD\lstver01s.sqlrpgle:25 - Include at line 25 found, to path 'QPROTO/http_h.rpgleinc'
QRPGLEMOD\lstver01s.sqlrpgle:24 - Include at line 24 found, to path 'QPROTO/sql_h.rpgleinc'
QRPGLEMOD\lstver01s.sqlrpgle:23 - Include at line 23 found, to path 'QPROTO/apiutl01s.rpgleinc'
QRPGLEMOD\lstver01s.sqlrpgle:22 - Include at line 22 found, to path 'QPROTO/lstver01s.rpgleinc'
QRPGLEMOD\lstver01s.sqlrpgle - has the BNDDIR keyword. 'binders' property in iproj.json should be used instead.
QRPGLEMOD\lstver01s.sqlrpgle:42 - No object found for reference 'VOVERPF'

ORDCON01S.MODULE: QRPGLEMOD\ordcon01s.sqlrpgle
QRPGLEMOD\ordcon01s.sqlrpgle:28 - Include at line 28 found, to path 'QPROTO/http_h.rpgleinc'
QRPGLEMOD\ordcon01s.sqlrpgle:27 - Include at line 27 found, to path 'QPROTO/sql_h.rpgleinc'
QRPGLEMOD\ordcon01s.sqlrpgle:26 - Include at line 26 found, to path 'QPROTO/apival01s.rpgleinc'
QRPGLEMOD\ordcon01s.sqlrpgle:25 - Include at line 25 found, to path 'QPROTO/apiutl01s.rpgleinc'
QRPGLEMOD\ordcon01s.sqlrpgle:24 - Include at line 24 found, to path 'QPROTO/ordcon01s.rpgleinc'
QRPGLEMOD\ordcon01s.sqlrpgle - has the BNDDIR keyword. 'binders' property in iproj.json should be used instead.

ORDPCK01S.MODULE: QRPGLEMOD\ordpck01s.sqlrpgle
QRPGLEMOD\ordpck01s.sqlrpgle:28 - Include at line 28 found, to path 'QPROTO/http_h.rpgleinc'
QRPGLEMOD\ordpck01s.sqlrpgle:27 - Include at line 27 found, to path 'QPROTO/sql_h.rpgleinc'
QRPGLEMOD\ordpck01s.sqlrpgle:26 - Include at line 26 found, to path 'QPROTO/apival01s.rpgleinc'
QRPGLEMOD\ordpck01s.sqlrpgle:25 - Include at line 25 found, to path 'QPROTO/apiutl01s.rpgleinc'
QRPGLEMOD\ordpck01s.sqlrpgle:24 - Include at line 24 found, to path 'QPROTO/ordpck01s.rpgleinc'
QRPGLEMOD\ordpck01s.sqlrpgle - has the BNDDIR keyword. 'binders' property in iproj.json should be used instead.

ORDPCK02S.MODULE: QRPGLEMOD\ordpck02s.sqlrpgle
QRPGLEMOD\ordpck02s.sqlrpgle:25 - Include at line 25 found, to path 'QPROTO/http_h.rpgleinc'
QRPGLEMOD\ordpck02s.sqlrpgle:24 - Include at line 24 found, to path 'QPROTO/sql_h.rpgleinc'
QRPGLEMOD\ordpck02s.sqlrpgle:23 - Include at line 23 found, to path 'QPROTO/apival01s.rpgleinc'
QRPGLEMOD\ordpck02s.sqlrpgle:22 - Include at line 22 found, to path 'QPROTO/apiutl01s.rpgleinc'
QRPGLEMOD\ordpck02s.sqlrpgle:21 - Include at line 21 found, to path 'QPROTO/ordpck02s.rpgleinc'
QRPGLEMOD\ordpck02s.sqlrpgle - has the BNDDIR keyword. 'binders' property in iproj.json should be used instead.

ORDPCK03S.MODULE: QRPGLEMOD\ordpck03s.sqlrpgle
QRPGLEMOD\ordpck03s.sqlrpgle:28 - Include at line 28 found, to path 'QPROTO/http_h.rpgleinc'
QRPGLEMOD\ordpck03s.sqlrpgle:27 - Include at line 27 found, to path 'QPROTO/sql_h.rpgleinc'
QRPGLEMOD\ordpck03s.sqlrpgle:26 - Include at line 26 found, to path 'QPROTO/apiutl01s.rpgleinc'
QRPGLEMOD\ordpck03s.sqlrpgle:25 - Include at line 25 found, to path 'QPROTO/ordpck03s.rpgleinc'
QRPGLEMOD\ordpck03s.sqlrpgle:67 - No object found for reference 'VOTWZL1'
QRPGLEMOD\ordpck03s.sqlrpgle:72 - No object found for reference 'VOTWZL1'
QRPGLEMOD\ordpck03s.sqlrpgle:76 - No object found for reference 'VOTWZL1'
QRPGLEMOD\ordpck03s.sqlrpgle:104 - No object found for reference 'VOMAGPF'
QRPGLEMOD\ordpck03s.sqlrpgle:117 - No object found for reference 'VOTWZPF'
QRPGLEMOD\ordpck03s.sqlrpgle:137 - No object found for reference 'VOORKLF'

TEST.PGM: QRPGLESRC\test.pgm.rpgle

VOKLATB.FILE: QSQLSRC\voklatb.table

VOORATB.FILE: QSQLSRC\vooratb.table

VOORKTB.FILE: QSQLSRC\voorktb.table

VOORTTB.FILE: QSQLSRC\voorttb.table














Resolving modules for APIERR01S.SRVPGM
QSRVSRC\apierr01s.bnd - Removed as target because no modules were found with matching exports.

Resolving modules for APIUTL01S.SRVPGM
QSRVSRC\apiutl01s.bnd - Removed as target because no modules were found with matching exports.

Resolving modules for APIVAL01S.SRVPGM
QSRVSRC\apival01s.bnd - Removed as target because no modules were found with matching exports.

Resolving modules for APIVAL02S.SRVPGM
QSRVSRC\apival02s.bnd - Removed as target because no modules were found with matching exports.

Resolving modules for APIVAL03S.SRVPGM
QSRVSRC\apival03s.bnd - Removed as target because no modules were found with matching exports.

Resolving modules for APIVAL04S.SRVPGM
QSRVSRC\apival04s.bnd - Removed as target because no modules were found with matching exports.

Resolving modules for APIVAL05S.SRVPGM
QSRVSRC\apival05s.bnd - Removed as target because no modules were found with matching exports.

Resolving modules for LSTVER01S.SRVPGM
QSRVSRC\lstver01s.bnd - Removed as target because no modules were found with matching exports.

Resolving modules for ORDCON01S.SRVPGM
QSRVSRC\ordcon01s.bnd - Removed as target because no modules were found with matching exports.

Resolving modules for ORDPCK01S.SRVPGM
QSRVSRC\ordpck01s.bnd - Removed as target because no modules were found with matching exports.

Resolving modules for ORDPCK02S.SRVPGM
QSRVSRC\ordpck02s.bnd - Removed as target because no modules were found with matching exports.

Resolving modules for ORDPCK03S.SRVPGM
QSRVSRC\ordpck03s.bnd - Removed as target because no modules were found with matching exports.
```

I'm guessing this is because of the last lines? These are the sources in my QRPGLEMOD for my service programs. I did use the Automatic rename when migrating the sources
![image](https://github.com/user-attachments/assets/0c800bc9-c57f-4a2e-846a-81310166588b)

**Comment by worksofliam** [comment]
> I'm guessing this is because of the last lines? These are the sources in my QRPGLEMOD for my service programs. I did use the Automatic rename when migrating the sources

That's not it. The names look ok!

To me, it seems like the binder source cannot find the exports from the modules. Do the module have exported procedures for sure?

**Comment by kaspervanderhulst** [comment]
I have changed these /copys to include the entire ifs path instead of just /QPROTO/.... but still the same result

**Comment by worksofliam** [comment]
@kaspervanderhulst Next, are you able to share `so --bf json` and share the file here? That should list all the exports that it found and help me connect the dots. Thanks!

**Comment by EASI-JHEI** [comment]
Hi @worksofliam, answering for my colleague here! :)
Please find attached the requested JSON output file
[sourceorbit.json](https://github.com/user-attachments/files/16694123/sourceorbit.json)

Kind regards

**Comment by kaspervanderhulst** [comment]
@worksofliam I've sent you a mail containing the service program!

**Comment by worksofliam** [comment]
@kaspervanderhulst Based on the source code that has been shared with me, I do believe there to be a bug. I will try and get a fix for you today.

**Comment by kaspervanderhulst** [comment]
@worksofliam Do you have any updates? :)

**Comment by worksofliam** [comment]
@kaspervanderhulst Sorry about the delay. I haven't had much time this week. But, I will try and get to it on Monday or Tuesday.

**Comment by worksofliam** [comment]
@kaspervanderhulst I think I found the source of the bug. I need to make a test case for it and maybe there will be a fix out today.

**Comment by worksofliam** [comment]
@kaspervanderhulst @EASI-JHEI I have just published SO 0.11.1 on npm. Please update and run it again!

**Comment by worksofliam** [comment]
Please re-open if the issue continues. Thanks!

**Comment by kaspervanderhulst** [comment]
I still seem to have problems. I have updated source orbit to the latest version, both on my IBM i system & my local system. But I am still having the same problem as before, where it seems like It is not recognizing the service programs and is not compiling them

**Comment by worksofliam** [comment]
@kaspervanderhulst Please share a newly generated JSON build file to see if I can spot any changes. Thanks!

```
so --bf json
```

**Comment by kaspervanderhulst** [comment]
I'm actually having trouble running this command with the newest version to generate the JSON on my local machine. 
I have the package installed globally as version 0.11.1. when running the so -bf json command, I'm getting this error:
[SO_error_0.11.1.txt](https://github.com/user-attachments/files/16851011/SO_error_0.11.1.txt)

I've tried to downgrade the package to 0.11.0 where I don't seem to have this problem. 
Thanks for all your help :)

**Comment by worksofliam** [comment]
@kaspervanderhulst That's related to your specific issue for sure! It's coming to the point where I am going to need more sources from you. Are you able to share `VOKLLV1.SQL` and any files that depend on it? Please feel free to use the same email.

**Comment by kaspervanderhulst** [comment]
I've sent an email with all requested info!

**Comment by kaspervanderhulst** [comment]
I can't seem to locate any files in the project that use VOKLLV1.SQL

**Comment by worksofliam** [comment]
Finally a fix is going to come out with 0.11.2. Sorry for the wait.
